### ISSUE TITLE
Needs for listing in k6 Extensions Registry 

### ISSUE THREAD

**Issue by javaducky** [deejiw/xk6-gcp#1]
Please address the following items to enable listing in the k6 Extensions Registry:

- add the `xk6` topic on your repository metadata
- add an `examples` directory containing k6 test scripts making use of your extension

For more information on these and other listing requirements, please take a look at the [registry requirements](https://k6.io/docs/extensions/explanations/about-the-extensions-registry/).

Relates to https://github.com/grafana/k6-docs/pull/1240 .

**Comment by deejiw** [comment]
Updated as per comment above.
https://github.com/deejiw/xk6-gcp/commit/3823ab2c36c8552d8da91dc2e27aa4d9d6870de4
